# Uncomment the next line to define a global platform for your project
# platform :ios, '10.15.7'

target 'address_duty' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


    pod 'KakaoSDKLink'
    pod 'KakaoSDKAuth'
#    pod 'SSZipArchive'
    pod 'Alamofire'
    pod 'Zip'	

  # Pods for address_duty

end


# 터미널 에서 pod install 후 곧 설치 후 터미널에 결과 이하 내용이다.

# peulogeulaemtimui-MacBook-Pro:address_duty program_team$ pod install
# Analyzing dependencies
# Downloading dependencies
# Installing Alamofire (5.2.2)
# Installing DynamicCodable (1.0)w
# Installing KakaoSDKAuth (2.0.1)
# Installing KakaoSDKCommon (2.0.1)
# Installing KakaoSDKLink (2.0.1)
# Installing KakaoSDKTemplate (2.0.1)
# Installing Zip (2.1.1)
# Generating Pods project
# Integrating client project

# [!] Please close any current Xcode sessions and use `address_duty.xcworkspace` for this project from now on.
# Pod installation complete! There are 4 dependencies from the Podfile and 7 total pods installed.
